<?php
/*
 * Copyright 2013 by Jerrick Hoang, Ivy Xing, Sam Roberts, James Cook, 
 * Johnny Coster, Judy Yang, Jackson Moniaga, Oliver Radwan, 
 * Maxwell Palmer, Nolan McNair, Taylor Talmage, and Allen Tucker. 
 * This program is part of RMH Homebase, which is free software.  It comes with 
 * absolutely no warranty. You can redistribute and/or modify it under the terms 
 * of the GNU General Public License as published by the Free Software Foundation
 * (see <http://www.gnu.org/licenses/ for more information).
 * 
 */

	session_start();
	session_cache_expire(30);
?>
<!-- page generated by the BowdoinRMH software package -->
<html>
	<head>
		<title>
			About
		</title>
		<link rel="stylesheet" href="styles.css" type="text/css" />
	</head>
	<body>
		<div id="container">
			<?PHP include('header.php');?>
			<div id="content">
				<p><strong>Background</strong><br /><br />
				<i>Homebase</i> is a web-based volunteer management and scheduling system originally developed in 2008 at Bowdoin College for
	      		the <a href="http://rmhcme.org" target="_blank">Ronald McDonald House in Portland, ME</a>. 
				
				<p>Later versions of <i>Homebase</i></a> were customized for the Ronald McDonald Houses in Providence, RI, Bangor, ME, and Boston, MA. Each of these
				versions was developed by a different student team, local RMH staff, and an instructor.
				
				<p>All versions of <i>Homebase</i> are freely supported by <a href="http://npfi.org" target="_blank">
				The Non-Profit FOSS Institute (NPFI)</a>, which "aims to build communities that develop and support customized 
				free and open source software (FOSS) applications that directly benefit the missions of humanitarian 
				non-profit organizations."
				
 				<p><b>System Access and Reuse</b><br /><br />
				Because <i>Homebase</i> must protect the privacy of individual RMH volunteers and staff, outside access to the system is
				restricted.  If you are an RMH staff member or volunteer and have forgotten your Username or Password, please contact the <a href="mailto:randerson@rmhcne.org">Volunteer Coordinator</a>.
                </p>
				<p> <i>Homebase</i> is free and open source software (see <a href="https://github.com/megandalster/homebasedemo2017" target="_blank">https://github.com/megandalster/homebasedemo2017</a>).  
				From this site, its source code can be freely downloaded and adapted
				 to fit the volunteer scheduling needs of other non-profits.  For more information about the capabilities or adaptability of <i>Homebase</i></i> to other settings, please 
				 contact either <a href="mailto:allen@npfi.org">Allen Tucker</a> or visit the website <a href="https://npfi.org" target="_blank">https://npfi.org</a>.
				</p> 
				
			</div>
		<?PHP include('footer.inc');?>
		</div>
	</body>
</html>
